/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DiscordSyntaxPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");
var import_view3 = require("@codemirror/view");

// ../core/dist/spoiler.js
function isEscaped(text, pos) {
  let count = 0;
  for (let i = pos - 1; i >= 0 && text[i] === "\\"; i--) {
    count++;
  }
  return count % 2 === 1;
}
function findCodeRanges(text) {
  const codeRanges = [];
  if (!text)
    return codeRanges;
  const lines = text.split("\n");
  let currentOffset = 0;
  let inFence = false;
  let fenceChar = "";
  let fenceLen = 0;
  let fenceStart = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineStart = currentOffset;
    const lineEnd = currentOffset + line.length;
    const fenceMatch = line.match(/^\s*(`{3,}|~{3,})/);
    if (fenceMatch) {
      const matchStr = fenceMatch[1];
      const char = matchStr[0];
      const len = matchStr.length;
      if (!inFence) {
        inFence = true;
        fenceChar = char;
        fenceLen = len;
        fenceStart = lineStart;
      } else if (char === fenceChar && len >= fenceLen) {
        inFence = false;
        codeRanges.push({ from: fenceStart, to: lineEnd, isFenced: true });
      }
    }
    if (inFence && i === lines.length - 1) {
      codeRanges.push({ from: fenceStart, to: lineEnd, isFenced: true });
    }
    currentOffset = lineEnd + 1;
  }
  currentOffset = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineStart = currentOffset;
    const lineEnd = currentOffset + line.length;
    const isLineInFence = codeRanges.some((r) => lineStart >= r.from && lineEnd <= r.to);
    if (!isLineInFence) {
      const backtickRegex = /(`+)/g;
      let match;
      let openBacktick = null;
      while ((match = backtickRegex.exec(line)) !== null) {
        const len = match[1].length;
        const index = lineStart + match.index;
        if (!openBacktick) {
          openBacktick = { len, index };
        } else if (openBacktick.len === len) {
          codeRanges.push({
            from: openBacktick.index,
            to: index + len,
            isFenced: false
          });
          openBacktick = null;
        }
      }
    }
    currentOffset = lineEnd + 1;
  }
  return codeRanges;
}
function isPosInCode(pos, codeRanges) {
  return codeRanges.some((r) => pos >= r.from && pos < r.to);
}
function findSpoilerRanges(text, baseOffset = 0) {
  const spoilers = [];
  if (!text || text.length < 4)
    return spoilers;
  const codeRanges = findCodeRanges(text);
  const isCode = (pos) => isPosInCode(pos, codeRanges);
  const blockRanges = [];
  const lines = text.split("\n");
  let currentOffset = 0;
  let blockStart = null;
  for (let i2 = 0; i2 < lines.length; i2++) {
    const line = lines[i2];
    const lineStart = currentOffset;
    const lineEnd = lineStart + line.length;
    currentOffset = lineEnd + 1;
    if (isCode(lineStart))
      continue;
    const blockMarkerMatch = line.match(/^\s*(\|\|)\s*$/);
    if (blockMarkerMatch) {
      const markerPos = lineStart + line.indexOf("||");
      if (!isCode(markerPos) && !isEscaped(text, markerPos)) {
        if (blockStart === null) {
          blockStart = {
            lineIdx: i2,
            offset: markerPos,
            contentFrom: lineEnd + 1 <= text.length ? lineEnd + 1 : lineEnd
          };
        } else {
          const contentTo = lineStart;
          spoilers.push({
            from: baseOffset + blockStart.offset,
            to: baseOffset + markerPos + 2,
            contentFrom: baseOffset + blockStart.contentFrom,
            contentTo: baseOffset + contentTo,
            isBlock: true
          });
          blockRanges.push({
            from: blockStart.offset,
            to: markerPos + 2
          });
          blockStart = null;
        }
      }
    }
  }
  const isInBlock = (pos) => blockRanges.some((r) => pos >= r.from && pos < r.to);
  let idx = text.indexOf("||");
  const candidates = [];
  while (idx !== -1) {
    if (!isCode(idx) && !isCode(idx + 1) && !isInBlock(idx) && !isEscaped(text, idx)) {
      candidates.push(idx);
    }
    idx = text.indexOf("||", idx + 2);
  }
  let i = 0;
  while (i < candidates.length - 1) {
    const startIdx = candidates[i];
    const nextChar = text[startIdx + 2];
    if (!nextChar || /\s/.test(nextChar)) {
      i++;
      continue;
    }
    let foundMatch = false;
    for (let j = i + 1; j < candidates.length; j++) {
      const endIdx = candidates[j];
      const prevChar = text[endIdx - 1];
      if (/\s/.test(prevChar)) {
        continue;
      }
      const content = text.slice(startIdx + 2, endIdx);
      if (content.includes("\n\n") || content.includes("\r\n\r\n")) {
        break;
      }
      const crossesFencedCode = codeRanges.some((r) => r.isFenced && startIdx < r.from && endIdx > r.to);
      if (crossesFencedCode) {
        continue;
      }
      if (content.length > 0) {
        spoilers.push({
          from: baseOffset + startIdx,
          to: baseOffset + endIdx + 2,
          contentFrom: baseOffset + startIdx + 2,
          contentTo: baseOffset + endIdx,
          isBlock: false
        });
        i = j + 1;
        foundMatch = true;
        break;
      }
    }
    if (!foundMatch) {
      i++;
    }
  }
  spoilers.sort((a, b) => a.from - b.from);
  return spoilers;
}

// ../core/dist/subtext.js
var SUBTEXT_MARKER = "-# ";
var SUBTEXT_MARKER_LEN = SUBTEXT_MARKER.length;
var SUBTEXT_LINE_REGEX = /^(?:\s*>\s*)*(?:\s*(?:[-*+]|\d+\.|-\s*\[[ xX]\])\s+)?\s*-# /;
function parseSubtextLine(lineText) {
  const match = lineText.match(SUBTEXT_LINE_REGEX);
  if (!match)
    return null;
  const fullMatched = match[0];
  const markerIdx = fullMatched.lastIndexOf(SUBTEXT_MARKER);
  if (markerIdx === -1)
    return null;
  const prefix = lineText.slice(0, markerIdx);
  const marker = SUBTEXT_MARKER;
  const content = lineText.slice(markerIdx + SUBTEXT_MARKER_LEN);
  return { prefix, marker, content };
}
function isSubtextLine(lineText) {
  return SUBTEXT_LINE_REGEX.test(lineText);
}
function stripSubtextPrefix(lineText) {
  const parsed = parseSubtextLine(lineText);
  if (parsed) {
    return parsed.prefix + parsed.content;
  }
  return lineText;
}
function hasSubtextMarker(text) {
  return /(?:^|\n)(?:\s*>\s*)*(?:\s*(?:[-*+]|\d+\.|-\s*\[[ xX]\])\s+)?\s*-# /.test(text);
}

// src/spoiler-post-processor.ts
function processSpoilers(element, doc = element.ownerDocument) {
  const fullText = element.textContent || "";
  const validRanges = findSpoilerRanges(fullText);
  if (validRanges.length === 0) return;
  const validPositions = /* @__PURE__ */ new Set();
  for (const r of validRanges) {
    validPositions.add(r.from);
    validPositions.add(r.to - 2);
  }
  function createSpoilerSpan() {
    const spoilerSpan = element.createEl("span", {
      cls: "note-flow-spoiler discord-syntax-spoiler",
      attr: {
        role: "button",
        tabindex: "0",
        "aria-expanded": "false",
        "aria-label": "Spoiler, click to reveal"
      }
    });
    if (spoilerSpan.parentNode) {
      spoilerSpan.parentNode.removeChild(spoilerSpan);
    }
    const innerSpan = spoilerSpan.createEl("span", {
      attr: {
        "aria-hidden": "true"
      }
    });
    function toggleSpoiler() {
      const isRevealed = spoilerSpan.classList.contains("is-revealed");
      if (isRevealed) {
        spoilerSpan.classList.remove("is-revealed");
        spoilerSpan.setAttribute("aria-expanded", "false");
        spoilerSpan.setAttribute("aria-label", "Spoiler, click to reveal");
        innerSpan.setAttribute("aria-hidden", "true");
      } else {
        spoilerSpan.classList.add("is-revealed");
        spoilerSpan.setAttribute("aria-expanded", "true");
        spoilerSpan.removeAttribute("aria-label");
        innerSpan.setAttribute("aria-hidden", "false");
      }
    }
    spoilerSpan.addEventListener("click", () => {
      toggleSpoiler();
    });
    spoilerSpan.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        toggleSpoiler();
      }
    });
    return spoilerSpan;
  }
  const markers = [];
  let currentPos = 0;
  function insertMarker(parent, node, text, index) {
    const beforeStr = text.slice(0, index);
    const afterStr = text.slice(index + 2);
    if (beforeStr) {
      parent.insertBefore(doc.createTextNode(beforeStr), node);
    }
    const marker = element.createEl("span", {
      attr: { "data-spoiler-marker": "true" }
    });
    if (marker.parentNode) {
      marker.parentNode.removeChild(marker);
    }
    parent.insertBefore(marker, node);
    markers.push(marker);
    if (afterStr) {
      const afterNode = doc.createTextNode(afterStr);
      parent.insertBefore(afterNode, node);
      return afterNode;
    }
    return null;
  }
  function collectMarkers(node) {
    if (node.nodeType === Node.TEXT_NODE) {
      let text = node.nodeValue || "";
      let searchFrom = 0;
      let idx = text.indexOf("||", searchFrom);
      if (idx !== -1 && node.parentNode) {
        const parent = node.parentNode;
        let remainingNode = node;
        while (remainingNode && idx !== -1) {
          const absPos = currentPos + idx;
          if (validPositions.has(absPos)) {
            const nextRemaining = insertMarker(
              parent,
              remainingNode,
              text,
              idx
            );
            parent.removeChild(remainingNode);
            remainingNode = nextRemaining;
            currentPos = absPos + 2;
            text = remainingNode ? remainingNode.nodeValue || "" : "";
            searchFrom = 0;
            idx = text ? text.indexOf("||", searchFrom) : -1;
          } else {
            searchFrom = idx + 2;
            idx = text.indexOf("||", searchFrom);
          }
        }
        if (remainingNode) {
          currentPos += (remainingNode.nodeValue || "").length;
        }
      } else {
        currentPos += text.length;
      }
    } else if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node;
      if (el.nodeName === "PRE" || el.nodeName === "CODE") {
        return;
      }
      if (el.classList.contains("note-flow-spoiler") || el.classList.contains("discord-syntax-spoiler")) {
        return;
      }
      for (const child of Array.from(node.childNodes)) {
        collectMarkers(child);
      }
    }
  }
  collectMarkers(element);
  for (let i = 0; i < markers.length - 1; i += 2) {
    const startMarker = markers[i];
    const endMarker = markers[i + 1];
    if (!startMarker || !endMarker) continue;
    const spoilerSpan = createSpoilerSpan();
    let usedRange = false;
    if (typeof doc.createRange === "function") {
      try {
        const range = doc.createRange();
        range.setStartAfter(startMarker);
        range.setEndBefore(endMarker);
        const fragment = range.extractContents();
        spoilerSpan.firstElementChild?.appendChild(fragment);
        if (startMarker.parentNode) {
          startMarker.parentNode.insertBefore(spoilerSpan, startMarker);
          startMarker.parentNode.removeChild(startMarker);
        }
        if (endMarker.parentNode) {
          endMarker.parentNode.removeChild(endMarker);
        }
        markers[i] = null;
        markers[i + 1] = null;
        usedRange = true;
      } catch {
        usedRange = false;
      }
    }
    if (!usedRange) {
      if (startMarker.parentNode && startMarker.parentNode === endMarker.parentNode) {
        const parent = startMarker.parentNode;
        parent.insertBefore(spoilerSpan, startMarker);
        const children = Array.from(parent.childNodes);
        const startIndex = children.indexOf(startMarker);
        const endIndex = children.indexOf(endMarker);
        for (let j = startIndex + 1; j < endIndex; j++) {
          const child = children[j];
          parent.removeChild(child);
          spoilerSpan.firstElementChild?.appendChild(child);
        }
        parent.removeChild(startMarker);
        parent.removeChild(endMarker);
        markers[i] = null;
        markers[i + 1] = null;
      }
    }
  }
  for (const marker of markers) {
    if (marker && marker.parentNode) {
      marker.parentNode.insertBefore(doc.createTextNode("||"), marker);
      marker.parentNode.removeChild(marker);
    }
  }
}

// src/spoiler-detector.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_language = require("@codemirror/language");
var obsidian = __toESM(require("obsidian"));
function getEditorLivePreviewField() {
  return obsidian.editorLivePreviewField ?? null;
}
var setSpoilerStateEffect = import_state.StateEffect.define();
var spoilerStateField = import_state.StateField.define({
  create() {
    return [];
  },
  update(value, tr) {
    let mapped = value.map((entry) => {
      const from = tr.changes.mapPos(entry.from, 1);
      const to = tr.changes.mapPos(entry.to, -1);
      return { ...entry, from, to };
    });
    for (const effect of tr.effects) {
      if (effect.is(setSpoilerStateEffect)) {
        const { from, to, state } = effect.value;
        mapped = mapped.filter(
          (entry) => !(entry.from === from && entry.to === to)
        );
        if (state !== "hidden") {
          mapped.push({ from, to, state });
        }
      }
    }
    return mapped;
  }
});
function isSelectionInSpoiler(state, from, to) {
  for (const range of state.selection.ranges) {
    if (range.empty) {
      if (range.head >= from && range.head < to) {
        return true;
      }
    } else {
      if (range.from < to && range.to > from) {
        return true;
      }
    }
  }
  return false;
}
function getSpoilerState(state, from, to) {
  const livePreviewField = getEditorLivePreviewField();
  if (livePreviewField) {
    const isLivePreview = state.field(livePreviewField, false);
    if (isLivePreview === false) {
      return "revealed";
    }
  }
  const entries = state.field(spoilerStateField, false) || [];
  const match = entries.find((e) => e.from === from && e.to === to);
  if (match) return match.state;
  const overlap = entries.find(
    (e) => Math.max(e.from, from) < Math.min(e.to, to)
  );
  if (overlap) return overlap.state;
  return "hidden";
}
function getSpoilerAtSelection(state) {
  const selection = state.selection;
  if (!selection.main.empty) return null;
  const pos = selection.main.head;
  const line = state.doc.lineAt(pos);
  const spoilers = findSpoilerRanges(line.text, line.from);
  for (const s of spoilers) {
    if (pos >= s.from && pos <= s.to) {
      return s;
    }
  }
  return null;
}
function isRangeInCodeNode(state, from, to) {
  try {
    const tree = (0, import_language.syntaxTree)(state);
    if (!tree) return false;
    let inCode = false;
    tree.iterate({
      from,
      to,
      enter(node) {
        const name = node.name.toLowerCase();
        if (name.includes("code") || name.includes("comment") || name.includes("math")) {
          inCode = true;
          return false;
        }
      }
    });
    return inCode;
  } catch {
    return false;
  }
}
function getSpoilerFragments(state, contentFrom, contentTo, spoilerIndex = 0) {
  if (contentFrom >= contentTo) return [];
  const pointsSet = /* @__PURE__ */ new Set();
  pointsSet.add(contentFrom);
  pointsSet.add(contentTo);
  const text = state.doc.sliceString(contentFrom, contentTo);
  for (let i = 0; i < text.length; i++) {
    if (text[i] === "\n") {
      const breakPos = contentFrom + i;
      pointsSet.add(breakPos);
      if (breakPos + 1 <= contentTo) {
        pointsSet.add(breakPos + 1);
      }
    }
  }
  try {
    const tree = (0, import_language.syntaxTree)(state);
    if (tree) {
      tree.iterate({
        from: contentFrom,
        to: contentTo,
        enter(node) {
          if (node.from > contentFrom && node.from < contentTo) {
            pointsSet.add(node.from);
          }
          if (node.to > contentFrom && node.to < contentTo) {
            pointsSet.add(node.to);
          }
        }
      });
    }
  } catch {
  }
  const sortedPoints = Array.from(pointsSet).sort((a, b) => a - b);
  const rawFragments = [];
  for (let i = 0; i < sortedPoints.length - 1; i++) {
    const fFrom = sortedPoints[i];
    const fTo = sortedPoints[i + 1];
    if (fFrom < fTo) {
      const sliceStr = state.doc.sliceString(fFrom, fTo);
      if (sliceStr !== "\n") {
        rawFragments.push({ from: fFrom, to: fTo });
      }
    }
  }
  if (rawFragments.length === 0) {
    return [];
  }
  return rawFragments.map((frag, idx) => {
    const isStart = idx === 0;
    const isEnd = idx === rawFragments.length - 1;
    const classNames = ["note-flow-spoiler", "discord-syntax-spoiler"];
    if (isStart && isEnd) {
      classNames.push(
        "note-flow-spoiler-single",
        "note-flow-spoiler-start",
        "note-flow-spoiler-end",
        "note-flow-spoiler-cap-left",
        "note-flow-spoiler-cap-right",
        "discord-syntax-spoiler-single",
        "discord-syntax-spoiler-start",
        "discord-syntax-spoiler-end",
        "discord-syntax-spoiler-cap-left",
        "discord-syntax-spoiler-cap-right"
      );
    } else if (isStart) {
      classNames.push(
        "note-flow-spoiler-start",
        "note-flow-spoiler-cap-left",
        "discord-syntax-spoiler-start",
        "discord-syntax-spoiler-cap-left"
      );
    } else if (isEnd) {
      classNames.push(
        "note-flow-spoiler-end",
        "note-flow-spoiler-cap-right",
        "discord-syntax-spoiler-end",
        "discord-syntax-spoiler-cap-right"
      );
    }
    classNames.push(`note-flow-spoiler-group-${spoilerIndex}`);
    return {
      from: frag.from,
      to: frag.to,
      isStart,
      isEnd,
      classes: classNames.join(" ")
    };
  });
}
function buildSpoilerDecorations(view) {
  const builder = new import_state.RangeSetBuilder();
  const state = view.state;
  let spoilerIndex = 0;
  for (const { from, to } of view.visibleRanges) {
    const text = state.doc.sliceString(from, to);
    const spoilers = findSpoilerRanges(text, from);
    for (const spoiler of spoilers) {
      spoilerIndex++;
      const spoilerState = getSpoilerState(state, spoiler.from, spoiler.to);
      if (spoilerState === "editing") {
        continue;
      }
      if (isSelectionInSpoiler(state, spoiler.from, spoiler.to)) {
        continue;
      }
      if (isRangeInCodeNode(state, spoiler.from, spoiler.to)) {
        continue;
      }
      const isRevealed = spoilerState === "revealed";
      builder.add(
        spoiler.from,
        spoiler.contentFrom,
        import_view.Decoration.mark({
          class: "note-flow-spoiler-delimiter note-flow-spoiler-hidden discord-syntax-spoiler-delimiter"
        })
      );
      const fragments = getSpoilerFragments(
        state,
        spoiler.contentFrom,
        spoiler.contentTo,
        spoilerIndex
      );
      if (fragments.length > 0) {
        for (const frag of fragments) {
          let classes = frag.classes;
          if (isRevealed) {
            classes += " is-revealed";
          }
          builder.add(
            frag.from,
            frag.to,
            import_view.Decoration.mark({
              class: classes,
              attributes: {
                "data-spoiler-id": `spoiler-${spoiler.from}`
              }
            })
          );
        }
      } else if (spoiler.contentFrom < spoiler.contentTo) {
        let classes = "note-flow-spoiler discord-syntax-spoiler note-flow-spoiler-single note-flow-spoiler-start note-flow-spoiler-end note-flow-spoiler-cap-left note-flow-spoiler-cap-right";
        if (isRevealed) {
          classes += " is-revealed";
        }
        builder.add(
          spoiler.contentFrom,
          spoiler.contentTo,
          import_view.Decoration.mark({
            class: classes,
            attributes: {
              "data-spoiler-id": `spoiler-${spoiler.from}`
            }
          })
        );
      }
      builder.add(
        spoiler.contentTo,
        spoiler.to,
        import_view.Decoration.mark({
          class: "note-flow-spoiler-delimiter note-flow-spoiler-hidden discord-syntax-spoiler-delimiter"
        })
      );
    }
  }
  return builder.finish();
}
var spoilerLivePreviewPlugin = import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.decorations = buildSpoilerDecorations(view);
    }
    update(update) {
      const oldState = update.startState.field(spoilerStateField, false);
      const newState = update.state.field(spoilerStateField, false);
      const stateChanged = oldState !== newState;
      if (update.docChanged || update.selectionSet || update.viewportChanged || stateChanged) {
        this.decorations = buildSpoilerDecorations(update.view);
      }
    }
  },
  {
    decorations: (v) => v.decorations,
    eventHandlers: {
      mousedown(event, view) {
        const livePreviewField = getEditorLivePreviewField();
        if (livePreviewField && view.state.field(livePreviewField, false) === false)
          return;
        const target = event.target;
        const pos = view.posAtCoords({ x: event.clientX, y: event.clientY });
        if (pos !== null) {
          const line = view.state.doc.lineAt(pos);
          const spoilers = findSpoilerRanges(line.text, line.from);
          const spoiler = spoilers.find((s) => pos >= s.from && pos <= s.to);
          if (spoiler) {
            const currentState = getSpoilerState(
              view.state,
              spoiler.from,
              spoiler.to
            );
            if (currentState === "hidden") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "revealed"
                })
              });
              return true;
            } else if (currentState === "revealed") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "editing"
                }),
                selection: { anchor: pos },
                scrollIntoView: true
              });
              view.focus();
              return true;
            } else if (currentState === "editing") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "hidden"
                }),
                selection: { anchor: spoiler.to },
                scrollIntoView: true
              });
              view.focus();
              return true;
            }
          }
        }
        const spoilerEl = target?.closest?.(
          "[data-spoiler-id]"
        );
        if (spoilerEl) {
          const spoilerId = spoilerEl.getAttribute("data-spoiler-id");
          if (spoilerId) {
            const fromStr = spoilerId.replace("spoiler-", "");
            const from = parseInt(fromStr, 10);
            if (!isNaN(from) && from >= 0 && from <= view.state.doc.length) {
              const line = view.state.doc.lineAt(from);
              const spoilers = findSpoilerRanges(line.text, line.from);
              const spoiler = spoilers.find((s) => s.from === from);
              if (spoiler) {
                const currentState = getSpoilerState(
                  view.state,
                  spoiler.from,
                  spoiler.to
                );
                if (currentState === "hidden") {
                  event.preventDefault();
                  view.dispatch({
                    effects: setSpoilerStateEffect.of({
                      from: spoiler.from,
                      to: spoiler.to,
                      state: "revealed"
                    })
                  });
                  return true;
                } else if (currentState === "revealed") {
                  event.preventDefault();
                  view.dispatch({
                    effects: setSpoilerStateEffect.of({
                      from: spoiler.from,
                      to: spoiler.to,
                      state: "editing"
                    }),
                    selection: { anchor: spoiler.contentFrom },
                    scrollIntoView: true
                  });
                  view.focus();
                  return true;
                } else if (currentState === "editing") {
                  event.preventDefault();
                  view.dispatch({
                    effects: setSpoilerStateEffect.of({
                      from: spoiler.from,
                      to: spoiler.to,
                      state: "hidden"
                    }),
                    selection: { anchor: spoiler.to },
                    scrollIntoView: true
                  });
                  view.focus();
                  return true;
                }
              }
            }
          }
        }
      },
      keydown(event, view) {
        const livePreviewField = getEditorLivePreviewField();
        if (livePreviewField && view.state.field(livePreviewField, false) === false)
          return;
        if (event.key === "Enter" || event.key === " ") {
          const spoiler = getSpoilerAtSelection(view.state);
          if (spoiler) {
            const currentState = getSpoilerState(
              view.state,
              spoiler.from,
              spoiler.to
            );
            if (currentState === "hidden") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "revealed"
                })
              });
              return true;
            } else if (currentState === "revealed") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "editing"
                }),
                selection: { anchor: spoiler.contentFrom },
                scrollIntoView: true
              });
              view.focus();
              return true;
            } else if (currentState === "editing") {
              event.preventDefault();
              view.dispatch({
                effects: setSpoilerStateEffect.of({
                  from: spoiler.from,
                  to: spoiler.to,
                  state: "hidden"
                }),
                selection: { anchor: spoiler.to },
                scrollIntoView: true
              });
              view.focus();
              return true;
            }
          }
        }
      },
      mouseover(event, view) {
        const target = event.target;
        const spoilerEl = target?.closest?.(
          "[data-spoiler-id]"
        );
        if (!spoilerEl) return;
        const spoilerId = spoilerEl.getAttribute("data-spoiler-id");
        if (!spoilerId || !/^[a-zA-Z0-9_-]+$/.test(spoilerId)) return;
        const relatedTarget = event.relatedTarget;
        const relatedSpoiler = relatedTarget?.closest?.(
          "[data-spoiler-id]"
        );
        const relatedId = relatedSpoiler?.getAttribute("data-spoiler-id");
        if (relatedId === spoilerId) return;
        const elements = view.dom.findAll(`[data-spoiler-id="${spoilerId}"]`);
        for (let i = 0; i < elements.length; i++) {
          const el = elements[i];
          if (el instanceof HTMLElement) {
            el.classList.add("is-hovered");
          }
        }
      },
      mouseout(event, view) {
        const target = event.target;
        const spoilerEl = target?.closest?.(
          "[data-spoiler-id]"
        );
        if (!spoilerEl) return;
        const spoilerId = spoilerEl.getAttribute("data-spoiler-id");
        if (!spoilerId || !/^[a-zA-Z0-9_-]+$/.test(spoilerId)) return;
        const relatedTarget = event.relatedTarget;
        const relatedSpoiler = relatedTarget?.closest?.(
          "[data-spoiler-id]"
        );
        const relatedId = relatedSpoiler?.getAttribute("data-spoiler-id");
        if (relatedId === spoilerId) return;
        const elements = view.dom.findAll(`[data-spoiler-id="${spoilerId}"]`);
        for (let i = 0; i < elements.length; i++) {
          const el = elements[i];
          if (el instanceof HTMLElement) {
            el.classList.remove("is-hovered");
          }
        }
      }
    }
  }
);
var spoilerLivePreviewExtension = [
  spoilerStateField,
  spoilerLivePreviewPlugin
];

// src/subtext-post-processor.ts
var SUBTEXT_CLASS = "discord-subtext";
function processSubtextParagraph(el) {
  const blockSelector = "p, ul, ol, div, blockquote";
  const finder = el;
  const hasChildBlock = typeof finder.find === "function" && finder.find(blockSelector) !== null;
  if (hasChildBlock) {
    return;
  }
  if (!elementMightHaveSubtext(el)) return;
  const children = Array.from(el.childNodes);
  const lines = splitIntoLines(children);
  const hasAny = lines.some((line) => lineIsSubtext(line));
  if (!hasAny) return;
  emptyContainer(el);
  for (let li = 0; li < lines.length; li++) {
    const line = lines[li];
    if (line.length === 0) continue;
    if (lineIsSubtext(line)) {
      const clone = cloneLine(line);
      stripMarkerFromFirstText(clone);
      const controls = [];
      const subtextNodes = [];
      for (const node of clone) {
        if (node.nodeType === ELEMENT_NODE_TYPE && (node.tagName === "INPUT" || node.classList?.contains("task-list-item-checkbox"))) {
          controls.push(node);
        } else {
          subtextNodes.push(node);
        }
      }
      for (const ctrl of controls) {
        el.appendChild(ctrl);
      }
      if (subtextNodes.length > 0) {
        const span = createSpanElement(el, SUBTEXT_CLASS);
        for (const node of subtextNodes) span.appendChild(node);
      }
    } else {
      for (const node of line) el.appendChild(node);
    }
  }
}
function createSpanElement(parent, cls) {
  if (typeof parent.createSpan === "function") {
    return parent.createSpan({ cls });
  }
  if (typeof parent.createEl === "function") {
    return parent.createEl("span", { cls });
  }
  const ownerDoc = parent.ownerDocument;
  if (ownerDoc && typeof ownerDoc.createElement === "function") {
    const span = ownerDoc.createElement("span");
    span.className = cls;
    parent.appendChild(span);
    return span;
  }
  return parent;
}
function emptyContainer(el) {
  const emptyable = el;
  if (typeof emptyable.empty === "function") {
    emptyable.empty();
  } else {
    while (el.firstChild) {
      el.removeChild(el.firstChild);
    }
  }
}
var TEXT_NODE_TYPE = typeof Node !== "undefined" ? Node.TEXT_NODE : 3;
var ELEMENT_NODE_TYPE = typeof Node !== "undefined" ? Node.ELEMENT_NODE : 1;
function elementMightHaveSubtext(el) {
  for (const child of Array.from(el.childNodes)) {
    if (child.nodeType === TEXT_NODE_TYPE) {
      const v = child.data;
      if (hasSubtextMarker(v)) return true;
    }
    if (child.nodeType === ELEMENT_NODE_TYPE) {
      const elem = child;
      if (elem.tagName === "BR" || elem.tagName === "INPUT" || elem.classList?.contains("task-list-item-checkbox")) {
        return true;
      }
    }
  }
  return false;
}
function splitIntoLines(nodes) {
  const lines = [[]];
  for (const node of nodes) {
    if (node.nodeType === TEXT_NODE_TYPE) {
      const text = node;
      const parts = text.data.split("\n");
      for (let i = 0; i < parts.length; i++) {
        if (parts[i].length > 0) {
          const frag = text.ownerDocument.createTextNode(parts[i]);
          lines[lines.length - 1].push(frag);
        }
        if (i < parts.length - 1) {
          lines.push([]);
        }
      }
    } else if (node.nodeType === ELEMENT_NODE_TYPE && node.tagName === "BR") {
      lines[lines.length - 1].push(node);
      lines.push([]);
    } else {
      lines[lines.length - 1].push(node);
    }
  }
  return lines;
}
function lineIsSubtext(line) {
  for (const node of line) {
    if (node.nodeType === TEXT_NODE_TYPE) {
      const data = node.data;
      if (isSubtextLine(data)) return true;
      if (data.trim().length === 0) continue;
      return false;
    }
    if (node.nodeType === ELEMENT_NODE_TYPE && (node.tagName === "BR" || node.tagName === "INPUT" || node.classList?.contains("task-list-item-checkbox"))) {
      continue;
    }
    return false;
  }
  return false;
}
function cloneLine(line) {
  return line.map((n) => n.cloneNode(true));
}
function stripMarkerFromFirstText(nodes) {
  for (const node of nodes) {
    if (node.nodeType === TEXT_NODE_TYPE) {
      const t = node;
      if (isSubtextLine(t.data)) {
        t.data = stripSubtextPrefix(t.data);
      }
      return;
    }
    if (node.nodeType === ELEMENT_NODE_TYPE && (node.tagName === "BR" || node.tagName === "INPUT" || node.classList?.contains("task-list-item-checkbox"))) {
      continue;
    }
    return;
  }
}

// src/subtext-live-preview.ts
var import_view2 = require("@codemirror/view");
var import_state2 = require("@codemirror/state");
var subtextLineMark = import_view2.Decoration.mark({ class: "discord-subtext" });
var subtextMarkerMark = import_view2.Decoration.mark({ class: "discord-subtext-marker" });
var subtextMarkerActiveMark = import_view2.Decoration.mark({
  class: "discord-subtext-marker-active"
});
var subtextEditorPlugin = import_view2.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.decorations = buildDecorations(view);
    }
    update(update) {
      if (update.docChanged || update.viewportChanged || update.selectionSet) {
        this.decorations = buildDecorations(update.view);
      }
    }
  },
  { decorations: (v) => v.decorations }
);
function collectActiveLineNumbers(view) {
  const doc = view.state.doc;
  const active = /* @__PURE__ */ new Set();
  for (const range of view.state.selection.ranges) {
    active.add(doc.lineAt(range.anchor).number);
    active.add(doc.lineAt(range.head).number);
  }
  return active;
}
function buildDecorations(view) {
  const builder = new import_state2.RangeSetBuilder();
  const doc = view.state.doc;
  const activeLines = collectActiveLineNumbers(view);
  for (const { from, to } of view.visibleRanges) {
    const startLine = doc.lineAt(from).number;
    const endLine = doc.lineAt(to).number;
    for (let ln = startLine; ln <= endLine; ln++) {
      const line = doc.line(ln);
      const text = line.text;
      const parsed = parseSubtextLine(text);
      if (!parsed) continue;
      const isActive = activeLines.has(ln);
      const markerFrom = line.from + parsed.prefix.length;
      const markerTo = markerFrom + SUBTEXT_MARKER_LEN;
      builder.add(
        markerFrom,
        markerTo,
        isActive ? subtextMarkerActiveMark : subtextMarkerMark
      );
      if (line.to > markerTo) {
        builder.add(markerTo, line.to, subtextLineMark);
      }
    }
  }
  return builder.finish();
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  enableSpoilers: true,
  enableSubtext: true,
  spoilerHiddenColor: "var(--background-modifier-hover, #36393f)",
  spoilerRevealedColor: "var(--background-modifier-active-hover, #4f545c)",
  spoilerTextColor: "var(--text-normal, #dcddde)",
  spoilerRadius: 4,
  spoilerPadding: 4,
  subtextColor: "var(--text-muted, #72767d)",
  subtextFontSize: 12,
  subtextOpacity: 0.75
};
function isPropertyResolver(obj) {
  return typeof obj === "object" && obj !== null && "getPropertyValue" in obj && typeof obj.getPropertyValue === "function";
}
function getPropertyResolver(targetEl) {
  if (!targetEl) {
    if (typeof window !== "undefined" && typeof window.getComputedStyle === "function") {
      const doc = window.document;
      const el = doc?.body ?? doc?.documentElement;
      if (el) {
        try {
          return window.getComputedStyle(el);
        } catch {
          return null;
        }
      }
    }
    return null;
  }
  if (isPropertyResolver(targetEl)) {
    return targetEl;
  }
  if (typeof targetEl === "object" && "ownerDocument" in targetEl) {
    const ownerDoc = targetEl.ownerDocument;
    const win = ownerDoc?.defaultView ?? (typeof window !== "undefined" ? window : null);
    if (win && typeof win.getComputedStyle === "function") {
      try {
        return win.getComputedStyle(targetEl);
      } catch {
        return null;
      }
    }
  }
  return null;
}
function parseVarExpression(expr) {
  const trimmed = expr.trim();
  if (!trimmed.startsWith("var(") || !trimmed.endsWith(")")) {
    return null;
  }
  const inner = trimmed.slice(4, -1).trim();
  const firstComma = inner.indexOf(",");
  if (firstComma === -1) {
    const varName2 = inner.trim();
    if (/^--[a-zA-Z0-9_-]+$/.test(varName2)) {
      return { varName: varName2 };
    }
    return null;
  }
  const varName = inner.slice(0, firstComma).trim();
  const fallback = inner.slice(firstComma + 1).trim();
  if (/^--[a-zA-Z0-9_-]+$/.test(varName)) {
    return { varName, fallback };
  }
  return null;
}
function resolveVarExpression(expr, resolver, depth = 0) {
  if (depth > 10) return expr;
  const parsed = parseVarExpression(expr);
  if (!parsed) {
    return expr.trim();
  }
  if (resolver) {
    const cssValue = resolver.getPropertyValue(parsed.varName).trim();
    if (cssValue) {
      return resolveVarExpression(cssValue, resolver, depth + 1);
    }
  }
  if (parsed.fallback !== void 0) {
    return resolveVarExpression(parsed.fallback, resolver, depth + 1);
  }
  return expr.trim();
}
function hslToHex(h, s, l) {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(h / 60 % 2 - 1));
  const m = l - c / 2;
  let r = 0;
  let g = 0;
  let b = 0;
  if (0 <= h && h < 60) {
    r = c;
    g = x;
    b = 0;
  } else if (60 <= h && h < 120) {
    r = x;
    g = c;
    b = 0;
  } else if (120 <= h && h < 180) {
    r = 0;
    g = c;
    b = x;
  } else if (180 <= h && h < 240) {
    r = 0;
    g = x;
    b = c;
  } else if (240 <= h && h < 300) {
    r = x;
    g = 0;
    b = c;
  } else if (300 <= h && h < 360) {
    r = c;
    g = 0;
    b = x;
  }
  const rHex = Math.round((r + m) * 255).toString(16).padStart(2, "0");
  const gHex = Math.round((g + m) * 255).toString(16).padStart(2, "0");
  const bHex = Math.round((b + m) * 255).toString(16).padStart(2, "0");
  return `#${rHex}${gHex}${bHex}`;
}
function parseColorToHex(str) {
  const trimmed = str.trim();
  const hex6 = trimmed.match(/^#([0-9a-fA-F]{6})$/);
  if (hex6) {
    return `#${hex6[1].toLowerCase()}`;
  }
  const hex3 = trimmed.match(/^#([0-9a-fA-F]{3})$/);
  if (hex3) {
    const [, h] = hex3;
    return `#${h[0]}${h[0]}${h[1]}${h[1]}${h[2]}${h[2]}`.toLowerCase();
  }
  const rgbMatch = trimmed.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i);
  if (rgbMatch) {
    const r = Math.min(255, Math.max(0, parseInt(rgbMatch[1], 10))).toString(16).padStart(2, "0");
    const g = Math.min(255, Math.max(0, parseInt(rgbMatch[2], 10))).toString(16).padStart(2, "0");
    const b = Math.min(255, Math.max(0, parseInt(rgbMatch[3], 10))).toString(16).padStart(2, "0");
    return `#${r}${g}${b}`;
  }
  const hslMatch = trimmed.match(
    /^hsla?\(\s*(\d+(?:\.\d+)?)(?:deg)?\s*,\s*(\d+(?:\.\d+)?)%\s*,\s*(\d+(?:\.\d+)?)%/i
  );
  if (hslMatch) {
    const h = (parseFloat(hslMatch[1]) % 360 + 360) % 360;
    const s = Math.min(1, Math.max(0, parseFloat(hslMatch[2]) / 100));
    const l = Math.min(1, Math.max(0, parseFloat(hslMatch[3]) / 100));
    return hslToHex(h, s, l);
  }
  const hexInStr = trimmed.match(/#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{3})/);
  if (hexInStr) {
    const raw = hexInStr[0];
    if (raw.length === 4) {
      return `#${raw[1]}${raw[1]}${raw[2]}${raw[2]}${raw[3]}${raw[3]}`.toLowerCase();
    }
    return raw.toLowerCase();
  }
  return null;
}
function resolveColorToHex(colorStr, targetEl) {
  if (!colorStr) return "#000000";
  const resolver = getPropertyResolver(targetEl);
  const resolvedExpr = resolveVarExpression(colorStr, resolver);
  const hex = parseColorToHex(resolvedExpr);
  return hex ?? "#000000";
}
function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}
function normalizeNumber(value, defaultValue, min, max) {
  if (typeof value !== "number" || isNaN(value) || !isFinite(value)) {
    return defaultValue;
  }
  return clamp(value, min, max);
}
function normalizeString(value, defaultValue) {
  if (typeof value !== "string" || value.trim().length === 0) {
    return defaultValue;
  }
  return value.trim();
}
function normalizeBoolean(value, defaultValue) {
  if (typeof value !== "boolean") {
    return defaultValue;
  }
  return value;
}
function normalizeSettings(data) {
  if (!data || typeof data !== "object") {
    return { ...DEFAULT_SETTINGS };
  }
  const record = data;
  return {
    enableSpoilers: normalizeBoolean(
      record.enableSpoilers,
      DEFAULT_SETTINGS.enableSpoilers
    ),
    enableSubtext: normalizeBoolean(
      record.enableSubtext,
      DEFAULT_SETTINGS.enableSubtext
    ),
    spoilerHiddenColor: normalizeString(
      record.spoilerHiddenColor,
      DEFAULT_SETTINGS.spoilerHiddenColor
    ),
    spoilerRevealedColor: normalizeString(
      record.spoilerRevealedColor,
      DEFAULT_SETTINGS.spoilerRevealedColor
    ),
    spoilerTextColor: normalizeString(
      record.spoilerTextColor,
      DEFAULT_SETTINGS.spoilerTextColor
    ),
    spoilerRadius: normalizeNumber(
      record.spoilerRadius,
      DEFAULT_SETTINGS.spoilerRadius,
      0,
      16
    ),
    spoilerPadding: normalizeNumber(
      record.spoilerPadding,
      DEFAULT_SETTINGS.spoilerPadding,
      0,
      12
    ),
    subtextColor: normalizeString(
      record.subtextColor,
      DEFAULT_SETTINGS.subtextColor
    ),
    subtextFontSize: normalizeNumber(
      record.subtextFontSize,
      DEFAULT_SETTINGS.subtextFontSize,
      8,
      24
    ),
    subtextOpacity: normalizeNumber(
      record.subtextOpacity,
      DEFAULT_SETTINGS.subtextOpacity,
      0.1,
      1
    )
  };
}
function resetAppearanceSettings(settings) {
  return {
    enableSpoilers: settings.enableSpoilers,
    enableSubtext: settings.enableSubtext,
    spoilerHiddenColor: DEFAULT_SETTINGS.spoilerHiddenColor,
    spoilerRevealedColor: DEFAULT_SETTINGS.spoilerRevealedColor,
    spoilerTextColor: DEFAULT_SETTINGS.spoilerTextColor,
    spoilerRadius: DEFAULT_SETTINGS.spoilerRadius,
    spoilerPadding: DEFAULT_SETTINGS.spoilerPadding,
    subtextColor: DEFAULT_SETTINGS.subtextColor,
    subtextFontSize: DEFAULT_SETTINGS.subtextFontSize,
    subtextOpacity: DEFAULT_SETTINGS.subtextOpacity
  };
}
function resetSingleAppearanceSetting(settings, key) {
  if (key === "enableSpoilers" || key === "enableSubtext") {
    return { ...settings };
  }
  return {
    ...settings,
    [key]: DEFAULT_SETTINGS[key]
  };
}
function getEnabledEditorExtensions(settings) {
  const extensions = [];
  if (settings.enableSubtext) {
    extensions.push(subtextEditorPlugin);
  }
  if (settings.enableSpoilers) {
    extensions.push(spoilerLivePreviewExtension);
  }
  return extensions;
}

// src/settings-tab.ts
var import_obsidian = require("obsidian");
function addSettingWithCssVar(container, name, descText, cssVar) {
  const setting = new import_obsidian.Setting(container).setName(name);
  setting.setDesc(descText + " CSS variable: ");
  const codeEl = setting.descEl.createEl("code", {
    text: cssVar,
    cls: "discord-syntax-code-var"
  });
  codeEl.setAttr("title", `CSS variable: ${cssVar}`);
  return setting;
}
var DiscordSyntaxSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.copyTimeoutId = null;
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [
      {
        name: "Enable Spoilers syntax",
        desc: "Enable ||spoiler|| syntax in Reading View and Live Preview.",
        control: { type: "toggle", key: "enableSpoilers" }
      },
      {
        name: "Enable Subtext syntax",
        desc: "Enable -# subtext syntax in Reading View and Live Preview.",
        control: { type: "toggle", key: "enableSubtext" }
      },
      {
        type: "group",
        heading: "Spoiler appearance",
        items: [
          {
            name: "Hidden background color",
            desc: "Background color of unrevealed spoilers. CSS variable: --discord-spoiler-hidden-bg",
            aliases: ["--discord-spoiler-hidden-bg"],
            control: {
              type: "color",
              key: "spoilerHiddenColor",
              disabled: () => !this.plugin.settings.enableSpoilers
            }
          },
          {
            name: "Revealed background color",
            desc: "Background color of revealed or hovered spoilers. CSS variable: --discord-spoiler-revealed-bg",
            aliases: ["--discord-spoiler-revealed-bg"],
            control: {
              type: "color",
              key: "spoilerRevealedColor",
              disabled: () => !this.plugin.settings.enableSpoilers
            }
          },
          {
            name: "Revealed text color",
            desc: "Text color of revealed spoilers. CSS variable: --discord-spoiler-text-color",
            aliases: ["--discord-spoiler-text-color"],
            control: {
              type: "color",
              key: "spoilerTextColor",
              disabled: () => !this.plugin.settings.enableSpoilers
            }
          },
          {
            name: "Corner radius (px)",
            desc: "Border radius for spoiler caps. CSS variable: --discord-spoiler-radius",
            aliases: ["--discord-spoiler-radius"],
            control: {
              type: "slider",
              key: "spoilerRadius",
              disabled: () => !this.plugin.settings.enableSpoilers,
              min: 0,
              max: 16,
              step: 1
            }
          },
          {
            name: "Cap padding (px)",
            desc: "Horizontal padding for outer spoiler edges. CSS variable: --discord-spoiler-padding",
            aliases: ["--discord-spoiler-padding"],
            control: {
              type: "slider",
              key: "spoilerPadding",
              disabled: () => !this.plugin.settings.enableSpoilers,
              min: 0,
              max: 12,
              step: 1
            }
          }
        ]
      },
      {
        type: "group",
        heading: "Subtext appearance",
        items: [
          {
            name: "Subtext color",
            desc: "Text color for subtext items. CSS variable: --discord-subtext-color",
            aliases: ["--discord-subtext-color"],
            control: {
              type: "color",
              key: "subtextColor",
              disabled: () => !this.plugin.settings.enableSubtext
            }
          },
          {
            name: "Subtext font size (px)",
            desc: "Font size for subtext items. CSS variable: --discord-subtext-font-size",
            aliases: ["--discord-subtext-font-size"],
            control: {
              type: "slider",
              key: "subtextFontSize",
              disabled: () => !this.plugin.settings.enableSubtext,
              min: 8,
              max: 24,
              step: 1
            }
          },
          {
            name: "Subtext opacity",
            desc: "Opacity for subtext items. CSS variable: --discord-subtext-opacity",
            aliases: ["--discord-subtext-opacity"],
            control: {
              type: "slider",
              key: "subtextOpacity",
              disabled: () => !this.plugin.settings.enableSubtext,
              min: 0.1,
              max: 1,
              step: 0.05
            }
          }
        ]
      },
      {
        name: "Reset appearance settings",
        desc: "Reset colors, size, opacity, radius, and padding to default values. Syntax toggles are preserved.",
        action: () => {
          this.plugin.settings = resetAppearanceSettings(this.plugin.settings);
          this.plugin.applyStyles(this.containerEl.ownerDocument?.body);
          this.update();
          void this.plugin.saveSettings();
        }
      }
    ];
  }
  getControlValue(key) {
    if (key === "spoilerHiddenColor" || key === "spoilerRevealedColor" || key === "spoilerTextColor" || key === "subtextColor") {
      return resolveColorToHex(
        this.plugin.settings[key],
        this.containerEl.ownerDocument?.body
      );
    }
    return super.getControlValue(key);
  }
  async setControlValue(key, value) {
    await super.setControlValue(key, value);
    if (key === "enableSpoilers" || key === "enableSubtext") {
      this.plugin.rebuildEditorExtensions();
      this.update();
    }
    this.plugin.applyStyles(this.containerEl.ownerDocument?.body);
  }
  hide() {
    if (this.copyTimeoutId !== null) {
      window.clearTimeout(this.copyTimeoutId);
      this.copyTimeoutId = null;
    }
    super.hide();
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    if (this.copyTimeoutId !== null) {
      window.clearTimeout(this.copyTimeoutId);
      this.copyTimeoutId = null;
    }
    new import_obsidian.Setting(containerEl).setName("Syntax").setHeading();
    const updateStyles = () => {
      const settingsBody = containerEl.ownerDocument?.body;
      this.plugin.applyStyles(settingsBody);
    };
    new import_obsidian.Setting(containerEl).setName("Enable Spoilers syntax").setDesc("Enable ||spoiler|| syntax in Reading View and Live Preview.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableSpoilers).onChange((value) => {
        if (this.plugin.settings.enableSpoilers === value) return;
        this.plugin.settings.enableSpoilers = value;
        this.plugin.rebuildEditorExtensions();
        updateSections();
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable Subtext syntax").setDesc("Enable -# subtext syntax in Reading View and Live Preview.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableSubtext).onChange((value) => {
        if (this.plugin.settings.enableSubtext === value) return;
        this.plugin.settings.enableSubtext = value;
        this.plugin.rebuildEditorExtensions();
        updateSections();
        void this.plugin.saveSettings();
      })
    );
    const spoilerDetails = containerEl.createEl("details", {
      cls: "discord-syntax-details"
    });
    spoilerDetails.createEl("summary", { text: "Spoiler appearance" });
    const spoilerContent = spoilerDetails.createEl("div", {
      cls: "discord-syntax-section-content"
    });
    const spoilerMsg = spoilerContent.createEl("div", {
      cls: "discord-syntax-disabled-msg",
      text: "Enable Spoilers syntax above to customize appearance."
    });
    const spoilerPreviewBox = spoilerContent.createEl("div", {
      cls: "markdown-rendered markdown-preview-view discord-syntax-preview-box"
    });
    const spoilerP = spoilerPreviewBox.createEl("p", {
      cls: "discord-syntax-preview-p"
    });
    spoilerP.createSpan({ text: "Preview: " });
    const spoilerEl = spoilerP.createSpan({
      cls: "discord-syntax-spoiler note-flow-spoiler discord-syntax-spoiler-single"
    });
    spoilerEl.setAttr("role", "button");
    spoilerEl.setAttr("tabindex", "0");
    spoilerEl.setAttr("aria-expanded", "false");
    spoilerEl.setAttr("aria-label", "Spoiler, click to reveal");
    const spoilerInner = spoilerEl.createSpan({
      cls: "discord-syntax-spoiler-content",
      text: "Hidden spoiler content"
    });
    spoilerInner.setAttr("aria-hidden", "true");
    spoilerEl.addEventListener("mouseenter", () => {
      spoilerEl.addClass("is-hovered");
    });
    spoilerEl.addEventListener("mouseleave", () => {
      spoilerEl.removeClass("is-hovered");
    });
    const toggleSpoilerPreview = () => {
      const isRevealed = spoilerEl.hasClass("is-revealed");
      if (isRevealed) {
        spoilerEl.removeClass("is-revealed");
        spoilerEl.setAttr("aria-expanded", "false");
        spoilerEl.setAttr("aria-label", "Spoiler, click to reveal");
        spoilerInner.setAttr("aria-hidden", "true");
      } else {
        spoilerEl.addClass("is-revealed");
        spoilerEl.setAttr("aria-expanded", "true");
        spoilerEl.removeAttribute("aria-label");
        spoilerInner.setAttr("aria-hidden", "false");
      }
    };
    spoilerEl.addEventListener("click", toggleSpoilerPreview);
    spoilerEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " " || e.key === "Spacebar") {
        e.preventDefault();
        toggleSpoilerPreview();
      }
    });
    const spoilerSettingsList = [];
    let hiddenColorPicker = null;
    const hiddenColorSetting = addSettingWithCssVar(
      spoilerContent,
      "Hidden background color",
      "Background color of unrevealed spoilers.",
      "--discord-spoiler-hidden-bg"
    ).addColorPicker((cp) => {
      hiddenColorPicker = cp;
      cp.setValue(
        resolveColorToHex(
          this.plugin.settings.spoilerHiddenColor,
          containerEl
        )
      ).onChange((val) => {
        this.plugin.settings.spoilerHiddenColor = val;
        updateStyles();
        void this.plugin.saveSettings();
      });
    }).addExtraButton((btn) => {
      btn.setIcon("rotate-ccw").setTooltip("Reset hidden background color to default").onClick(() => {
        this.plugin.settings = resetSingleAppearanceSetting(
          this.plugin.settings,
          "spoilerHiddenColor"
        );
        updateStyles();
        if (hiddenColorPicker) {
          hiddenColorPicker.setValue(
            resolveColorToHex(
              DEFAULT_SETTINGS.spoilerHiddenColor,
              containerEl
            )
          );
        }
        void this.plugin.saveSettings();
      });
    });
    spoilerSettingsList.push(hiddenColorSetting);
    let revealedColorPicker = null;
    const revealedColorSetting = addSettingWithCssVar(
      spoilerContent,
      "Revealed background color",
      "Background color of revealed or hovered spoilers.",
      "--discord-spoiler-revealed-bg"
    ).addColorPicker((cp) => {
      revealedColorPicker = cp;
      cp.setValue(
        resolveColorToHex(
          this.plugin.settings.spoilerRevealedColor,
          containerEl
        )
      ).onChange((val) => {
        this.plugin.settings.spoilerRevealedColor = val;
        updateStyles();
        void this.plugin.saveSettings();
      });
    }).addExtraButton((btn) => {
      btn.setIcon("rotate-ccw").setTooltip("Reset revealed background color to default").onClick(() => {
        this.plugin.settings = resetSingleAppearanceSetting(
          this.plugin.settings,
          "spoilerRevealedColor"
        );
        updateStyles();
        if (revealedColorPicker) {
          revealedColorPicker.setValue(
            resolveColorToHex(
              DEFAULT_SETTINGS.spoilerRevealedColor,
              containerEl
            )
          );
        }
        void this.plugin.saveSettings();
      });
    });
    spoilerSettingsList.push(revealedColorSetting);
    let textColorPicker = null;
    const textColorSetting = addSettingWithCssVar(
      spoilerContent,
      "Revealed text color",
      "Text color of revealed spoilers.",
      "--discord-spoiler-text-color"
    ).addColorPicker((cp) => {
      textColorPicker = cp;
      cp.setValue(
        resolveColorToHex(this.plugin.settings.spoilerTextColor, containerEl)
      ).onChange((val) => {
        this.plugin.settings.spoilerTextColor = val;
        updateStyles();
        void this.plugin.saveSettings();
      });
    }).addExtraButton((btn) => {
      btn.setIcon("rotate-ccw").setTooltip("Reset revealed text color to default").onClick(() => {
        this.plugin.settings = resetSingleAppearanceSetting(
          this.plugin.settings,
          "spoilerTextColor"
        );
        updateStyles();
        if (textColorPicker) {
          textColorPicker.setValue(
            resolveColorToHex(
              DEFAULT_SETTINGS.spoilerTextColor,
              containerEl
            )
          );
        }
        void this.plugin.saveSettings();
      });
    });
    spoilerSettingsList.push(textColorSetting);
    let radiusSlider = null;
    const radiusSetting = addSettingWithCssVar(
      spoilerContent,
      "Corner radius (px)",
      "Border radius for spoiler caps (0 to 16px).",
      "--discord-spoiler-radius"
    ).addSlider((slider) => {
      radiusSlider = slider;
      slider.setLimits(0, 16, 1).setValue(this.plugin.settings.spoilerRadius).setDynamicTooltip().onChange((val) => {
        this.plugin.settings.spoilerRadius = val;
        updateStyles();
        void this.plugin.saveSettings();
      });
    }).addExtraButton((btn) => {
      btn.setIcon("rotate-ccw").setTooltip("Reset corner radius to default").onClick(() => {
        this.plugin.settings = resetSingleAppearanceSetting(
          this.plugin.settings,
          "spoilerRadius"
        );
        updateStyles();
        if (radiusSlider) {
          radiusSlider.setValue(DEFAULT_SETTINGS.spoilerRadius);
        }
        void this.plugin.saveSettings();
      });
    });
    spoilerSettingsList.push(radiusSetting);
    let paddingSlider = null;
    const paddingSetting = addSettingWithCssVar(
      spoilerContent,
      "Cap padding (px)",
      "Horizontal padding for outer spoiler edges (0 to 12px).",
      "--discord-spoiler-padding"
    ).addSlider((slider) => {
      paddingSlider = slider;
      slider.setLimits(0, 12, 1).setValue(this.plugin.settings.spoilerPadding).setDynamicTooltip().onChange((val) => {
        this.plugin.settings.spoilerPadding = val;
        updateStyles();
        void this.plugin.saveSettings();
      });
    }).addExtraButton((btn) => {
      btn.setIcon("rotate-ccw").setTooltip("Reset cap padding to default").onClick(() => {
        this.plugin.settings = resetSingleAppearanceSetting(
          this.plugin.settings,
          "spoilerPadding"
        );
        updateStyles();
        if (paddingSlider) {
          paddingSlider.setValue(DEFAULT_SETTINGS.spoilerPadding);
        }
        void this.plugin.saveSettings();
      });
    });
    spoilerSettingsList.push(paddingSetting);
    const subtextDetails = containerEl.createEl("details", {
      cls: "discord-syntax-details"
    });
    subtextDetails.createEl("summary", { text: "Subtext appearance" });
    const subtextContent = subtextDetails.createEl("div", {
      cls: "discord-syntax-section-content"
    });
    const subtextMsg = subtextContent.createEl("div", {
      cls: "discord-syntax-disabled-msg",
      text: "Enable Subtext syntax above to customize appearance."
    });
    const subtextPreviewBox = subtextContent.createEl("div", {
      cls: "markdown-rendered markdown-preview-view discord-syntax-preview-box"
    });
    subtextPreviewBox.createEl("p", {
      cls: "discord-syntax-preview-p discord-syntax-preview-p-margin",
      text: "This is a regular body text line in note."
    });
    const subtextP2 = subtextPreviewBox.createEl("p", {
      cls: "discord-syntax-preview-p"
    });
    subtextP2.createSpan({
      cls: "discord-subtext",
      text: "-# This is a secondary subtext line preview."
    });
    const subtextSettingsList = [];
    let subtextColorPicker = null;
    const subtextColorSetting = addSettingWithCssVar(
      subtextContent,
      "Subtext color",
      "Text color for subtext items.",
      "--discord-subtext-color"
    ).addColorPicker((cp) => {
      subtextColorPicker = cp;
      cp.setValue(
        resolveColorToHex(this.plugin.settings.subtextColor, containerEl)
      ).onChange((val) => {
        this.plugin.settings.subtextColor = val;
        updateStyles();
        void this.plugin.saveSettings();
      });
    }).addExtraButton((btn) => {
      btn.setIcon("rotate-ccw").setTooltip("Reset subtext color to default").onClick(() => {
        this.plugin.settings = resetSingleAppearanceSetting(
          this.plugin.settings,
          "subtextColor"
        );
        updateStyles();
        if (subtextColorPicker) {
          subtextColorPicker.setValue(
            resolveColorToHex(DEFAULT_SETTINGS.subtextColor, containerEl)
          );
        }
        void this.plugin.saveSettings();
      });
    });
    subtextSettingsList.push(subtextColorSetting);
    let subtextFontSizeSlider = null;
    const subtextFontSizeSetting = addSettingWithCssVar(
      subtextContent,
      "Subtext font size (px)",
      "Font size for subtext items (8 to 24px).",
      "--discord-subtext-font-size"
    ).addSlider((slider) => {
      subtextFontSizeSlider = slider;
      slider.setLimits(8, 24, 1).setValue(this.plugin.settings.subtextFontSize).setDynamicTooltip().onChange((val) => {
        this.plugin.settings.subtextFontSize = val;
        updateStyles();
        void this.plugin.saveSettings();
      });
    }).addExtraButton((btn) => {
      btn.setIcon("rotate-ccw").setTooltip("Reset subtext font size to default").onClick(() => {
        this.plugin.settings = resetSingleAppearanceSetting(
          this.plugin.settings,
          "subtextFontSize"
        );
        updateStyles();
        if (subtextFontSizeSlider) {
          subtextFontSizeSlider.setValue(DEFAULT_SETTINGS.subtextFontSize);
        }
        void this.plugin.saveSettings();
      });
    });
    subtextSettingsList.push(subtextFontSizeSetting);
    let subtextOpacitySlider = null;
    const subtextOpacitySetting = addSettingWithCssVar(
      subtextContent,
      "Subtext opacity",
      "Opacity for subtext items (0.1 to 1.0).",
      "--discord-subtext-opacity"
    ).addSlider((slider) => {
      subtextOpacitySlider = slider;
      slider.setLimits(0.1, 1, 0.05).setValue(this.plugin.settings.subtextOpacity).setDynamicTooltip().onChange((val) => {
        this.plugin.settings.subtextOpacity = val;
        updateStyles();
        void this.plugin.saveSettings();
      });
    }).addExtraButton((btn) => {
      btn.setIcon("rotate-ccw").setTooltip("Reset subtext opacity to default").onClick(() => {
        this.plugin.settings = resetSingleAppearanceSetting(
          this.plugin.settings,
          "subtextOpacity"
        );
        updateStyles();
        if (subtextOpacitySlider) {
          subtextOpacitySlider.setValue(DEFAULT_SETTINGS.subtextOpacity);
        }
        void this.plugin.saveSettings();
      });
    });
    subtextSettingsList.push(subtextOpacitySetting);
    const advancedDetails = containerEl.createEl("details", {
      cls: "discord-syntax-details"
    });
    advancedDetails.createEl("summary", { text: "Advanced" });
    const advancedContent = advancedDetails.createEl("div", {
      cls: "discord-syntax-section-content"
    });
    new import_obsidian.Setting(advancedContent).setName("Reset appearance settings").setDesc(
      "Reset colors, size, opacity, radius, and padding to default values. Syntax toggles are preserved."
    ).addButton(
      (btn) => btn.setButtonText("Reset to defaults").setWarning().onClick(() => {
        this.plugin.settings = resetAppearanceSettings(
          this.plugin.settings
        );
        updateStyles();
        this.display();
        void this.plugin.saveSettings();
      })
    );
    const cssGuideEl = advancedContent.createEl("div", {
      cls: "discord-syntax-css-guide"
    });
    new import_obsidian.Setting(cssGuideEl).setName("Custom CSS & Theme Customization").setHeading();
    cssGuideEl.createEl("p", {
      text: "The plugin sets inline CSS variables on document.body when custom settings are saved. To override these variables without !important, target element selectors directly (such as .discord-syntax-spoiler, .note-flow-spoiler, .discord-subtext, or .discord-subtext-marker)."
    });
    const exampleSnippet = `/* Custom CSS snippet for spoilers (covering main & alias classes) */
.discord-syntax-spoiler,
.note-flow-spoiler {
  --discord-spoiler-hidden-bg: #2b2d31;
  --discord-spoiler-revealed-bg: #404249;
  --discord-spoiler-text-color: #f2f3f5;
  --discord-spoiler-radius: 6px;
  --discord-spoiler-padding: 4px;
}

/* Custom CSS snippet for subtext and subtext markers */
.discord-subtext,
.discord-subtext-marker,
.discord-subtext-marker-active {
  --discord-subtext-color: #949ba4;
  --discord-subtext-font-size: 12px;
  --discord-subtext-opacity: 0.8;
}`;
    const codePre = cssGuideEl.createEl("pre", {
      cls: "discord-syntax-code-block"
    });
    codePre.createEl("code", { text: exampleSnippet });
    new import_obsidian.Setting(cssGuideEl).setName("Copy example CSS snippet").setDesc(
      "Copy standard CSS snippet for theme customization to clipboard."
    ).addButton(
      (btn) => btn.setButtonText("Copy snippet").onClick(() => {
        const doCopy = async () => {
          try {
            await navigator.clipboard.writeText(exampleSnippet);
            btn.setButtonText("Copied!");
            if (this.copyTimeoutId !== null) {
              window.clearTimeout(this.copyTimeoutId);
            }
            this.copyTimeoutId = window.setTimeout(() => {
              this.copyTimeoutId = null;
              if (btn.buttonEl && btn.buttonEl.isConnected) {
                btn.setButtonText("Copy snippet");
              }
            }, 2e3);
          } catch {
            new import_obsidian.Notice("Failed to copy CSS snippet to clipboard.");
          }
        };
        void doCopy();
      })
    );
    const updateSections = () => {
      const spoilersEnabled = this.plugin.settings.enableSpoilers;
      if (!spoilersEnabled) {
        spoilerDetails.removeAttribute("open");
        spoilerDetails.addClass("is-disabled");
        spoilerMsg.removeClass("u-hidden");
        spoilerSettingsList.forEach((s) => {
          s.setDisabled(true);
        });
      } else {
        spoilerDetails.removeClass("is-disabled");
        spoilerMsg.addClass("u-hidden");
        spoilerSettingsList.forEach((s) => {
          s.setDisabled(false);
        });
      }
      const subtextEnabled = this.plugin.settings.enableSubtext;
      if (!subtextEnabled) {
        subtextDetails.removeAttribute("open");
        subtextDetails.addClass("is-disabled");
        subtextMsg.removeClass("u-hidden");
        subtextSettingsList.forEach((s) => {
          s.setDisabled(true);
        });
      } else {
        subtextDetails.removeClass("is-disabled");
        subtextMsg.addClass("u-hidden");
        subtextSettingsList.forEach((s) => {
          s.setDisabled(false);
        });
      }
    };
    updateSections();
    updateStyles();
  }
};

// src/style-manager.ts
var STYLE_VARIABLE_KEYS = [
  "--discord-spoiler-hidden-bg",
  "--discord-spoiler-revealed-bg",
  "--discord-spoiler-text-color",
  "--discord-spoiler-radius",
  "--discord-spoiler-padding",
  "--discord-subtext-color",
  "--discord-subtext-font-size",
  "--discord-subtext-opacity"
];
var STYLE_CLASS_NAME = "discord-syntax-enabled";
function serializeStyleVariables(settings) {
  return {
    "--discord-spoiler-hidden-bg": settings.spoilerHiddenColor,
    "--discord-spoiler-revealed-bg": settings.spoilerRevealedColor,
    "--discord-spoiler-text-color": settings.spoilerTextColor,
    "--discord-spoiler-radius": `${settings.spoilerRadius}px`,
    "--discord-spoiler-padding": `${settings.spoilerPadding}px`,
    "--discord-subtext-color": settings.subtextColor,
    "--discord-subtext-font-size": `${settings.subtextFontSize}px`,
    "--discord-subtext-opacity": `${settings.subtextOpacity}`
  };
}
function applyStyleVariables(settings, targetEl) {
  if (!targetEl || !targetEl.style) return;
  const vars = serializeStyleVariables(settings);
  for (const [key, val] of Object.entries(vars)) {
    targetEl.style.setProperty(key, val);
  }
  if (targetEl.classList) {
    targetEl.classList.add(STYLE_CLASS_NAME);
  }
}
function removeStyleVariables(targetEl) {
  if (!targetEl || !targetEl.style) return;
  for (const key of STYLE_VARIABLE_KEYS) {
    targetEl.style.removeProperty(key);
  }
  if (targetEl.classList) {
    targetEl.classList.remove(STYLE_CLASS_NAME);
  }
}

// src/main.ts
var DiscordSyntaxPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.editorExtensions = [];
    this.saveQueue = Promise.resolve();
    this.styledBodies = /* @__PURE__ */ new Set();
  }
  async onload() {
    await this.loadSettings();
    this.applyStyles();
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.applyStyles())
    );
    this.registerEvent(
      this.app.workspace.on("window-open", () => this.applyStyles())
    );
    this.registerMarkdownPostProcessor((element) => {
      if (this.settings.enableSubtext) {
        const selector = "p, li, .callout-content";
        const targets = /* @__PURE__ */ new Set();
        if (typeof element.matches === "function" && element.matches(selector)) {
          targets.add(element);
        }
        const finder = element;
        if (typeof finder.findAll === "function") {
          const children = finder.findAll(selector);
          for (let i = 0; i < children.length; i++) {
            targets.add(children[i]);
          }
        }
        for (const target of targets) {
          processSubtextParagraph(target);
        }
      }
      if (this.settings.enableSpoilers) {
        processSpoilers(element);
      }
    });
    this.editorExtensions.push(...getEnabledEditorExtensions(this.settings));
    this.registerEditorExtension(this.editorExtensions);
    this.addSettingTab(new DiscordSyntaxSettingTab(this.app, this));
    this.addCommand({
      id: "toggle-all-spoilers",
      name: "Toggle all spoilers in active note",
      callback: () => {
        if (!this.settings.enableSpoilers) {
          new import_obsidian2.Notice("Spoiler syntax is disabled in settings");
          return;
        }
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
        if (!activeView) return;
        const mode = activeView.getMode();
        if (mode === "preview") {
          const container = activeView.contentEl.find(".markdown-preview-view") ?? activeView.contentEl;
          if (!container) return;
          const spoilers = container.findAll(
            ".note-flow-spoiler, .discord-syntax-spoiler"
          );
          if (spoilers.length === 0) return;
          let anyHidden = false;
          for (let i = 0; i < spoilers.length; i++) {
            if (!spoilers[i].classList.contains("is-revealed")) {
              anyHidden = true;
              break;
            }
          }
          const targetReveal = anyHidden;
          for (let i = 0; i < spoilers.length; i++) {
            const el = spoilers[i];
            const inner = el.firstElementChild;
            if (targetReveal) {
              el.classList.add("is-revealed");
              el.setAttribute("aria-expanded", "true");
              el.removeAttribute("aria-label");
              if (inner) inner.setAttribute("aria-hidden", "false");
            } else {
              el.classList.remove("is-revealed");
              el.setAttribute("aria-expanded", "false");
              el.setAttribute("aria-label", "Spoiler, click to reveal");
              if (inner) inner.setAttribute("aria-hidden", "true");
            }
          }
        } else if (mode === "source") {
          const cmEl = activeView.contentEl.find(".cm-editor");
          const cm = cmEl ? import_view3.EditorView.findFromDOM(cmEl) : null;
          if (!cm || typeof cm.dispatch !== "function") return;
          const state = cm.state;
          const text = state.doc.toString();
          const spoilers = findSpoilerRanges(text);
          if (spoilers.length === 0) return;
          let anyHidden = false;
          for (const s of spoilers) {
            const sState = getSpoilerState(state, s.from, s.to);
            if (sState === "hidden") {
              anyHidden = true;
              break;
            }
          }
          const targetState = anyHidden ? "revealed" : "hidden";
          const effects = spoilers.map(
            (s) => setSpoilerStateEffect.of({
              from: s.from,
              to: s.to,
              state: targetState
            })
          );
          let newSelection;
          if (state.selection.main.empty) {
            const pos = state.selection.main.head;
            for (const s of spoilers) {
              if (pos >= s.from && pos <= s.to) {
                newSelection = { anchor: s.to };
                break;
              }
            }
          }
          cm.dispatch({
            effects,
            selection: newSelection ? { anchor: newSelection.anchor } : void 0
          });
        }
      }
    });
  }
  async loadSettings() {
    const loadedData = await this.loadData();
    this.settings = normalizeSettings(loadedData);
  }
  async saveSettings() {
    const queue = this.saveQueue.then(async () => {
      await this.saveData(this.settings);
    }).catch((err) => {
      console.error("Discord Syntax: Failed to save settings", err);
    });
    this.saveQueue = queue;
    return queue;
  }
  getTargetBodies() {
    const bodies = /* @__PURE__ */ new Set();
    if (typeof document !== "undefined" && document.body) {
      bodies.add(document.body);
    }
    if (typeof activeDocument !== "undefined" && activeDocument.body) {
      bodies.add(activeDocument.body);
    }
    if (this.app?.workspace?.containerEl?.ownerDocument?.body) {
      bodies.add(this.app.workspace.containerEl.ownerDocument.body);
    }
    if (typeof this.app?.workspace?.iterateAllLeaves === "function") {
      this.app.workspace.iterateAllLeaves((leaf) => {
        const body = leaf.view?.containerEl?.ownerDocument?.body;
        if (body) {
          bodies.add(body);
        }
      });
    }
    return Array.from(bodies);
  }
  applyStyles(extraTarget) {
    const bodies = this.getTargetBodies();
    if (extraTarget) {
      bodies.push(extraTarget);
    }
    for (const body of bodies) {
      this.styledBodies.add(body);
      applyStyleVariables(this.settings, body);
    }
  }
  rebuildEditorExtensions() {
    this.editorExtensions.length = 0;
    this.editorExtensions.push(...getEnabledEditorExtensions(this.settings));
    this.app.workspace.updateOptions();
  }
  onunload() {
    const bodiesToClean = /* @__PURE__ */ new Set([
      ...this.getTargetBodies(),
      ...this.styledBodies
    ]);
    for (const body of bodiesToClean) {
      removeStyleVariables(body);
    }
    this.styledBodies.clear();
  }
};

/* nosourcemap */